const colorTheme = {
  gray: "#5E6B78",
  lightGray: "#B5B5C8",
  lightGray0: "#9E9E9E",
  lightGray4: "#f3f4f6",
  borderColor: "#E2E2E2",
  successBarColor: "#0D921B",
  pendingBarColor: "#DDDDDD",
  dividerColor: "#f7f7f7",
  bgSuccessAlert: "#B9FBC0",
  circleProgressBarcolor: "#EAE0DF",
  scoreSuccessStarColor: "#2BB639",
  QuationsBoxBg: "#FEF1EE",
  QuationsBoxContentBg: "#FFF8F7",
  scoreCardBg1: "#FFE5B3",
  scoreCardIcon1: "#E78D12",
  scoreCardBg2: "#FEEFEB",
  scoreCardIcon2: "#F57B7B",
  reportDetailsSubheaderBg: "#FFCAAC",
  achiverBoxBg: "#FFF9F9",
};
export default colorTheme;
