import colorThemeCore from './colorTheme'

const colorTheme = {
  ...colorThemeCore,
  primary: '#F87558',
  cardText: '#383739',
  cardBg: '#C9AFF4',
  cardCloseIcon: '#7F9DAC',
  ReportsTitle: '#FFC9AB',
  present: '#2BB639',
  absent: '#F57B7B',
  unmarked: '#B5B5C8',
  unmarkedLight: '#F0F0F4',
  default: '#d3d3e5',
  checkBlankcircle: '#FFEB3B',
  bgSuccessAlert: '#B9FBC0',
  successAlertText: '#0D921B',
  reportCardBgLight: '#FFF9F9',
  reportCardBg: '#FFCAAC',
  reportCardCloseIcon: '#875234',
  reportBoxBg: '#FFF8F7',
  reportBorder: '#ede7e6',
  bgMarkAttendance: '#9C27B0',
  messageSent: '#B1B1BF',
  messageAlert: '#373839',
  messageInfo: '#7C7E82',
  date: '#373839',
  dateText: '#9C9EA0',
  success: '#0D921B',
  warning: '#FFC369',
  danger: '#F57B7B',
  present: '#0d911c',
  absent: '#F57B7B',
  presentLight: '#F3FAF4',
  absentLight: '#FFF8F7',
  presentCardCompareText: '#FA8129',
  presentCardCompareBg: '#ECFBF2',
  presentCardCompareBorder: '#cae3ce',
  presentCardText: '#07C71B',
  absentCardCompareBg: '#FFF6F6',
  absentCardCompareBorder: '#dfcbcb',
  absentCardText: '#F57B7B',
  absentCardCompareText: '#FA8129',
  weekCardCompareBg: '#FFF8F7',
  presentCardBg: '#DFFDE2',
  presentCardBorder: '#cae3ce',
  absentCardBg: '#FDE7E7',
  absentCardBorder: '#dfcbcb',
  reportbtnBg: '#FEEFEB',
  reportbtnBorder: '#FCC6BA',
  attendanceCardBg: '#C9AFF4',
  studentCardBg: '#B9FBC0',
  studentCardText: '#5B7E5F'
}
export default colorTheme
