import moment from "moment";
export const timeTables = [
  {
    id: "1",
    start: moment().format("Y-MM-DD") + " 08:30",
    end: moment().format("Y-MM-DD") + " 09:25",
    title: "MATHEMATICS",
    subTitle: "Class V, Sec B",
  },
  {
    id: "2",
    start: moment().format("Y-MM-DD") + " 09:30",
    end: moment().format("Y-MM-DD") + " 10:25",
    title: "MATHEMATICS",
    subTitle: "Class V, Sec C",
  },
  {
    id: "3",
    start: moment().format("Y-MM-DD") + " 10:30",
    end: moment().format("Y-MM-DD") + " 11:25",
    title: "SPECIAL_DANCE_MID_DROUP",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "4",
    start: moment().format("Y-MM-DD") + " 11:30",
    end: moment().format("Y-MM-DD") + " 12:25",
    title: "FREE_PERIOD",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "5",
    start: moment().format("Y-MM-DD") + " 12:30",
    end: moment().format("Y-MM-DD") + " 13:25",
    title: "SCIENCE",
    subTitle: "Class VI, Sec A",
    activeMenu: true,
  },
  {
    id: "6",
    start: moment().format("Y-MM-DD") + " 13:30",
    end: moment().format("Y-MM-DD") + " 14:25",
    title: "SUBSTITUTION",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "7",
    start: moment().format("Y-MM-DD") + " 14:30",
    end: moment().format("Y-MM-DD") + " 15:25",
    title: "FREE_PERIOD",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "8",
    start: moment().format("Y-MM-DD") + " 15:30",
    end: moment().format("Y-MM-DD") + " 16:25",
    title: "MATHS",
    subTitle: "Class VI, Sec A",
  },
  {
    id: "1",
    start: moment().add(1, "days").format("Y-MM-DD") + " 08:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 09:25",
    title: "MATHS",
    subTitle: "Class V, Sec B",
  },
  {
    id: "2",
    start: moment().add(1, "days").format("Y-MM-DD") + " 09:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 10:25",
    title: "MATHS",
    subTitle: "Class V, Sec C",
  },
  {
    id: "3",
    start: moment().add(1, "days").format("Y-MM-DD") + " 10:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 11:25",
    title: "SPECIAL_DANCE_MID_DROUP",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "4",
    start: moment().add(1, "days").format("Y-MM-DD") + " 11:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 12:25",
    title: "FREE_PERIOD",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "5",
    start: moment().add(1, "days").format("Y-MM-DD") + " 12:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 13:25",
    title: "SCIENCE",
    subTitle: "Class VI, Sec A",
  },
  {
    id: "6",
    start: moment().add(1, "days").format("Y-MM-DD") + " 13:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 14:25",
    title: "SUBSTITUTION",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "7",
    start: moment().add(1, "days").format("Y-MM-DD") + " 14:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 15:25",
    title: "FREE_PERIOD",
    subTitle: "N/A",
    rightIcon: "More2LineIcon",
  },
  {
    id: "8",
    start: moment().add(1, "days").format("Y-MM-DD") + " 15:30",
    end: moment().add(1, "days").format("Y-MM-DD") + " 16:25",
    title: "MATHS",
    subTitle: "Class VI, Sec A",
  },
];

export const sampleClassData = [
  { id: "1", className: "Class I", route: "1" },
  { id: "2", className: "Class II", route: "2" },
  { id: "3", className: "Class III", route: "3" },
];
