export const worksheets = [
  {
    id: 1,
    image: "",
    name: "Addition",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 2,
    image: "",
    name: "Subtraction",
    class: "V",
    likes: "6",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "20",
    chapter: "2",
    downloads: "2",
  },
];

export const worksheetsList = [
  {
    id: 1,
    image: "",
    name: "Addition",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 2,
    image: "",
    name: "Subtraction",
    class: "V",
    likes: "6",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "20",
    chapter: "2",
    downloads: "2",
  },
  {
    id: 3,
    image: "",
    name: "Subtraction",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 2,
    image: "",
    name: "Addition",
    class: "V",
    likes: "6",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "20",
    chapter: "2",
    downloads: "2",
  },
  {
    id: 5,
    image: "",
    name: "Addition",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 6,
    image: "",
    name: "Subtraction",
    class: "V",
    likes: "6",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "20",
    chapter: "2",
    downloads: "2",
  },
];
