export const worksheets = [
  {
    id: 1,
    image: "",
    heading: "Learning Made Easy",
    subHeading: "NCERT Workbook",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 2,
    image: "",
    heading: "Learning Made Easy",
    subHeading: "NCERT Workbook",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "Worksheets help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
];
