export const courses = [
  {
    id: 1,
    state: "Ongoing",
    name: "Addition",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    image: "",
    duration: "10",
    source: "Diksha",
    dueDate: "27 Jul, 2022",
    takenBy: "27 Jul, 2022",
  },
  {
    id: 2,
    state: "Assigned",
    name: "Subtraction",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    image: "",
    duration: "10",
    source: "Diksha",
    dueDate: "27 Jul, 2022",
    takenBy: "27 Jul, 2022",
  },
  {
    id: 3,
    state: "Completed",
    name: "Subtraction",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    image: "",
    duration: "10",
    source: "Diksha",
    dueDate: "27 Jul, 2022",
    takenBy: "27 Jul, 2022",
  },
];

export const courseList = [
  {
    id: 1,
    image: "",
    name: "Addition",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 2,
    image: "",
    name: "Subtraction",
    class: "V",
    likes: "6",
    comments: "0",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "20",
    chapter: "2",
    downloads: "2",
  },
  {
    id: 3,
    image: "",
    name: "Subtraction",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 2,
    image: "",
    name: "Addition",
    class: "V",
    likes: "6",
    comments: "0",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "20",
    chapter: "2",
    downloads: "2",
  },
  {
    id: 5,
    image: "",
    name: "Addition",
    class: "V",
    likes: "4",
    comments: "0",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "30",
    chapter: "3",
    downloads: "3",
  },
  {
    id: 6,
    image: "",
    name: "Subtraction",
    class: "V",
    likes: "6",
    comments: "0",
    description:
      "courses help the kids in exploring multiple concepts and ideas. They develop fine motor skills and logical thinking.",
    subject: "Math",
    level: "Beginner",
    grade: "VI",
    questions: "20",
    chapter: "2",
    downloads: "2",
  },
];
